import pytest
from unittest.mock import patch, MagicMock, AsyncMock
import uuid
import os
from fastapi import status
from fastapi.testclient import TestClient

from app.main import app
from app.db.session import get_db

@pytest.fixture
def mock_db():
    db = AsyncMock()
    # Mock return value of db.execute(...) to be an object with .scalars().first() returning None by default
    mock_execute = MagicMock()
    mock_execute.scalars.return_value.first.return_value = None
    db.execute.return_value = mock_execute
    return db

@pytest.fixture
def client(mock_db):
    async def override_get_db():
        yield mock_db
    
    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()

def test_upload_document_success(client, mock_db):
    """
    Test successful document upload.
    Verifies that with a valid JWT token, the route:
    1. Validates size/type.
    2. Uploads the file to storage.
    3. Indexes the document.
    4. Saves the Document model to NeonDB.
    5. Returns a 201 Created status and a valid DocumentResponse metadata payload.
    """
    user_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    mock_summary = "This is a document summary generated by LLM."
    mock_index_result = {
        "summary": mock_summary,
        "text": "Parsed file content text",
        "index": MagicMock()
    }

    # Patch the JWT verification middleware and the backend upload/index functions
    with patch("app.auth.middleware.decode_token", return_value=mock_payload), \
         patch("app.routers.documents.upload_file", return_value=f"{user_uuid}/mock-doc-id/test.txt") as mock_upload, \
         patch("app.routers.documents.index_document", return_value=mock_index_result) as mock_index:

        files = {"file": ("test.txt", b"Hello world text document", "text/plain")}
        headers = {"Authorization": "Bearer dummy-token"}
        
        response = client.post("/documents/upload", files=files, headers=headers)
        
        assert response.status_code == status.HTTP_201_CREATED
        data = response.json()
        assert "id" in data
        assert data["user_id"] == str(user_uuid)
        assert data["filename"] == "test.txt"
        assert data["size_bytes"] == len(b"Hello world text document")
        assert data["status"] == "completed"
        assert data["summary"] == mock_summary
        assert "uploaded_at" in data
        assert "expiry_at" in data

        # Verify downstream upload & indexing were triggered with correct parameters
        mock_upload.assert_called_once()
        called_args = mock_upload.call_args[1]
        assert called_args["user_id"] == user_uuid
        assert called_args["filename"] == "test.txt"
        assert called_args["data"] == b"Hello world text document"

        mock_index.assert_called_once()
        index_args = mock_index.call_args[1]
        assert index_args["user_id"] == user_uuid
        assert index_args["filename"] == "test.txt"
        assert index_args["file_bytes"] == b"Hello world text document"

        # Verify database session calls
        mock_db.add.assert_called_once()
        mock_db.commit.assert_called_once()

def test_upload_document_with_chat_success(client, mock_db):
    """
    Test successful document upload linked to an existing Chat with default name 'New Chat'.
    Verifies that the chat's current_doc_id is updated and its title is derived from the summary.
    """
    user_uuid = uuid.uuid4()
    chat_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    mock_summary = "This is a document summary. It discusses agent frameworks."
    mock_index_result = {
        "summary": mock_summary,
        "text": "Parsed file content text",
        "index": MagicMock()
    }

    # Mock chat record in database
    mock_chat = MagicMock()
    mock_chat.id = chat_uuid
    mock_chat.user_id = user_uuid
    mock_chat.title = "New Chat"
    mock_chat.current_doc_id = None

    # Mock execute to return this chat
    mock_execute = MagicMock()
    mock_execute.scalars.return_value.first.return_value = mock_chat
    mock_db.execute.return_value = mock_execute

    with patch("app.auth.middleware.decode_token", return_value=mock_payload), \
         patch("app.routers.documents.upload_file", return_value=f"{user_uuid}/mock-doc-id/test.txt"), \
         patch("app.routers.documents.index_document", return_value=mock_index_result):

        files = {"file": ("test.txt", b"Hello world text document", "text/plain")}
        data = {"chat_id": str(chat_uuid)}
        headers = {"Authorization": "Bearer dummy-token"}
        
        response = client.post("/documents/upload", files=files, data=data, headers=headers)
        
        assert response.status_code == status.HTTP_201_CREATED
        assert mock_chat.current_doc_id is not None
        # Title should be derived from first sentence (<= 60 chars)
        assert mock_chat.title == "This is a document summary"
        mock_db.commit.assert_called_once()

def test_upload_document_chat_not_found(client, mock_db):
    """
    Test document upload with a chat ID that does not exist or does not belong to the user.
    """
    user_uuid = uuid.uuid4()
    chat_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    # Mock execute to return None (chat not found / not owned)
    mock_execute = MagicMock()
    mock_execute.scalars.return_value.first.return_value = None
    mock_db.execute.return_value = mock_execute

    with patch("app.auth.middleware.decode_token", return_value=mock_payload):
        files = {"file": ("test.txt", b"Hello world text document", "text/plain")}
        data = {"chat_id": str(chat_uuid)}
        headers = {"Authorization": "Bearer dummy-token"}
        
        response = client.post("/documents/upload", files=files, data=data, headers=headers)
        assert response.status_code == status.HTTP_404_NOT_FOUND
        assert response.json()["detail"]["error"]["code"] == "CHAT_NOT_FOUND"

def test_upload_document_chat_invalid_uuid(client, mock_db):
    """
    Test document upload with an invalid UUID format for chat_id.
    """
    user_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    with patch("app.auth.middleware.decode_token", return_value=mock_payload):
        files = {"file": ("test.txt", b"Hello world text document", "text/plain")}
        data = {"chat_id": "not-a-valid-uuid"}
        headers = {"Authorization": "Bearer dummy-token"}
        
        response = client.post("/documents/upload", files=files, data=data, headers=headers)
        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert response.json()["detail"]["error"]["code"] == "INVALID_CHAT_ID"

def test_upload_document_db_error_rollback(client, mock_db):
    """
    Test document upload when database insertion fails.
    Verifies that the uploaded storage object and local index files are correctly cleaned up.
    """
    user_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    mock_summary = "This is a document summary."
    mock_index_result = {
        "summary": mock_summary,
        "text": "Parsed file content text",
        "index": MagicMock()
    }

    # Make db commit raise an exception
    mock_db.commit.side_effect = Exception("DB Connection Error")

    with patch("app.auth.middleware.decode_token", return_value=mock_payload), \
         patch("app.routers.documents.upload_file", return_value=f"{user_uuid}/mock-doc-id/test.txt") as mock_upload, \
         patch("app.routers.documents.delete_file") as mock_delete, \
         patch("app.routers.documents.index_document", return_value=mock_index_result), \
         patch("shutil.rmtree") as mock_rmtree, \
         patch("os.path.exists", return_value=True):

        files = {"file": ("test.txt", b"Hello world text document", "text/plain")}
        headers = {"Authorization": "Bearer dummy-token"}
        
        with pytest.raises(Exception, match="DB Connection Error"):
            client.post("/documents/upload", files=files, headers=headers)

        # Verify that delete_file was called to clean up storage
        mock_delete.assert_called_once()
        # Verify that local index folder was cleaned up
        mock_rmtree.assert_called_once()
        mock_db.rollback.assert_called_once()

def test_upload_document_unauthorized(client):
    """
    Test document upload request without standard JWT authentication.
    Verifies that the JWTMiddleware rejects the call before reaching the router.
    """
    files = {"file": ("test.txt", b"Hello world text document", "text/plain")}
    response = client.post("/documents/upload", files=files)
    assert response.status_code == status.HTTP_401_UNAUTHORIZED
    data = response.json()
    assert data["detail"]["error"]["code"] == "UNAUTHORIZED"

def test_upload_document_invalid_extension(client):
    """
    Test document upload with an unsupported file extension.
    Verifies that the request is rejected with a 400 Bad Request.
    """
    user_uuid = uuid.uuid4()
    mock_payload = {"sub": str(user_uuid), "email": "test@example.com"}

    with patch("app.auth.middleware.decode_token", return_value=mock_payload):
        files = {"file": ("test.png", b"fake png bytes", "image/png")}
        headers = {"Authorization": "Bearer dummy-token"}
        
        response = client.post("/documents/upload", files=files, headers=headers)
        assert response.status_code == status.HTTP_400_BAD_REQUEST
        data = response.json()
        assert data["detail"]["error"]["code"] == "INVALID_FILE_TYPE"

def test_upload_document_empty_file(client):
    """
    Test document upload with an empty file payload.
    Verifies that it is rejected with a 400 Bad Request.
    """
    user_uuid = uuid.uuid4()
    mock_payload = {"sub": str(user_uuid), "email": "test@example.com"}

    with patch("app.auth.middleware.decode_token", return_value=mock_payload):
        files = {"file": ("test.txt", b"", "text/plain")}
        headers = {"Authorization": "Bearer dummy-token"}
        
        response = client.post("/documents/upload", files=files, headers=headers)
        assert response.status_code == status.HTTP_400_BAD_REQUEST
        data = response.json()
        assert data["detail"]["error"]["code"] == "EMPTY_FILE"


from datetime import datetime

def test_get_document_success(client, mock_db):
    """
    Test successful retrieval of document metadata.
    """
    user_uuid = uuid.uuid4()
    doc_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    mock_doc = MagicMock()
    mock_doc.id = doc_uuid
    mock_doc.user_id = user_uuid
    mock_doc.filename = "test.txt"
    mock_doc.size_bytes = 100
    mock_doc.status = "completed"
    mock_doc.summary = "A document summary"
    mock_doc.uploaded_at = datetime.now()
    mock_doc.expiry_at = datetime.now()

    mock_execute = MagicMock()
    mock_execute.scalars.return_value.first.return_value = mock_doc
    mock_db.execute.return_value = mock_execute

    with patch("app.auth.middleware.decode_token", return_value=mock_payload):
        headers = {"Authorization": "Bearer dummy-token"}
        response = client.get(f"/documents/{doc_uuid}", headers=headers)

        assert response.status_code == status.HTTP_200_OK
        data = response.json()
        assert data["id"] == str(doc_uuid)
        assert data["filename"] == "test.txt"
        assert data["summary"] == "A document summary"


def test_get_document_not_found(client, mock_db):
    """
    Test retrieval of a document that does not exist or does not belong to the user.
    Verifies that a 404 status code is returned (hiding document existence for other tenants).
    """
    user_uuid = uuid.uuid4()
    doc_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    mock_execute = MagicMock()
    mock_execute.scalars.return_value.first.return_value = None
    mock_db.execute.return_value = mock_execute

    with patch("app.auth.middleware.decode_token", return_value=mock_payload):
        headers = {"Authorization": "Bearer dummy-token"}
        response = client.get(f"/documents/{doc_uuid}", headers=headers)

        assert response.status_code == status.HTTP_404_NOT_FOUND
        assert response.json()["detail"]["error"]["code"] == "DOCUMENT_NOT_FOUND"


def test_delete_document_success(client, mock_db):
    """
    Test successful deletion of a document.
    Verifies that DB record is deleted, commit is called, and Tigris storage and local vector indices are cleared.
    """
    user_uuid = uuid.uuid4()
    doc_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    mock_doc = MagicMock()
    mock_doc.id = doc_uuid
    mock_doc.user_id = user_uuid
    mock_doc.r2_key = "user/doc/test.txt"

    mock_execute = MagicMock()
    mock_execute.scalars.return_value.first.return_value = mock_doc
    mock_db.execute.return_value = mock_execute

    with patch("app.auth.middleware.decode_token", return_value=mock_payload), \
         patch("app.routers.documents.delete_file") as mock_delete, \
         patch("shutil.rmtree") as mock_rmtree, \
         patch("os.path.exists", return_value=True):
        
        headers = {"Authorization": "Bearer dummy-token"}
        response = client.delete(f"/documents/{doc_uuid}", headers=headers)

        assert response.status_code == status.HTTP_204_NO_CONTENT
        mock_db.delete.assert_called_once_with(mock_doc)
        mock_db.commit.assert_called_once()
        mock_delete.assert_called_once_with("user/doc/test.txt")
        mock_rmtree.assert_called_once()


def test_delete_document_not_found(client, mock_db):
    """
    Test deleting a document that does not exist or does not belong to the user.
    """
    user_uuid = uuid.uuid4()
    doc_uuid = uuid.uuid4()
    mock_payload = {
        "sub": str(user_uuid),
        "email": "test@example.com"
    }

    mock_execute = MagicMock()
    mock_execute.scalars.return_value.first.return_value = None
    mock_db.execute.return_value = mock_execute

    with patch("app.auth.middleware.decode_token", return_value=mock_payload):
        headers = {"Authorization": "Bearer dummy-token"}
        response = client.delete(f"/documents/{doc_uuid}", headers=headers)

        assert response.status_code == status.HTTP_404_NOT_FOUND
        assert response.json()["detail"]["error"]["code"] == "DOCUMENT_NOT_FOUND"
        mock_db.delete.assert_not_called()
        mock_db.commit.assert_not_called()


def test_upload_document_empty_document_error(client, mock_db):
    """
    Test document upload when index_document raises ValueError("EMPTY_DOCUMENT").
    Verifies that the API catches it and returns HTTP 422 Unprocessable Entity.
    """
    user_uuid = uuid.uuid4()
    mock_payload = {"sub": str(user_uuid), "email": "test@example.com"}

    with patch("app.auth.middleware.decode_token", return_value=mock_payload), \
         patch("app.routers.documents.upload_file", return_value=f"{user_uuid}/mock-doc-id/test.pdf"), \
         patch("app.routers.documents.index_document", side_effect=ValueError("EMPTY_DOCUMENT")):

        files = {"file": ("test.pdf", b"PDF file with no extractable text", "application/pdf")}
        headers = {"Authorization": "Bearer dummy-token"}

        response = client.post("/documents/upload", files=files, headers=headers)
        assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY
        assert "Could not extract text from this document" in response.json()["detail"]


